services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: nest_app
    platform: linux/amd64  # 👈 Це нове!
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
